apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      initContainers:
        - name: migrate
          image: net168/php82-nginx-laravel:latest
          command:
            [
              "sh",
              "-c",
              "sleep 10 && php /var/www/html/artisan migrate --force",
            ]
          env:
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: chansuvannet-db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: Hello@123
      containers:
        - name: web
          image: net168/php82-nginx-laravel:latest
          ports:
            - containerPort: 8080
            - containerPort: 22
          env:
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: chansuvannet-db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: Hello@123
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Hello@123
            - name: MYSQL_DATABASE
              value: chansuvannet-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: mysql-data
          emptyDir: {}
